<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Riot API</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/skeleton.css">
    <link rel="stylesheet" href="/css/main.css">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="one-half column" style="margin-top: 25%">
                <h4>API</h4>
                <?php if(isset($model)): ?>
                <p>Updated <?=$model?> data</p>
                <?php else:?>
                <p><a href="/api/champions">/champions</a> - update champions data</p>
                <p><a href="/api/items">/items</a> - update items data</p>
                <p><a href="/api/match_list">/match_list</a> - update games data</p>
                <p><a href="/api/summoner_spells">/summoner_spells</a> - update summoner spells data</p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</body>

</html>
